name: Build and push image (stable)

env:
  repository: "madebythepinshub/rtappdotio"
  tag: ${{ github.event.release.tag_name }}
  # Edit this if you forked the repo
  # otherwise, comment out everything about Quay.io
  QUAYIO_USERNAME: madebythepinshub+github_actions

on:
  release:
    types: [published]

jobs:
  docker-ci-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ env.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          registry: quay.io
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          username: RecapTimeBot
          password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          registry: ghcr.io
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ env.repository }}:${{ env.tag }}, ghcr.io/${{ env.repository }}:latest, ghcr.io/${{ env.repository }}:stable, quay.io/${{ env.repository }}:${{ env.tag }}, quay.io/${{ env.repository }}:latest, quay.io/${{ env.repository }}:stable
