name: Build and push image (develop)

env:
  repository: "madebythepinshub/rtappdotio"
  tag: "develop"
  # Edit this if you forked the repo
  # otherwise, comment out everything about Quay.io
  QUAYIO_USERNAME: madebythepinshub+github_actions

on:
  push:
    branches:
      - develop

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ env.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
          registry: quay.io
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: RecapTimeBot
          password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
          registry: ghcr.io


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            quay.io/${{ env.repository }}:${{ env.tag }}
            ghcr.io/${{ env.repository }}:${{ env.tag }}
